[target.aarch64-linux-android]
ar = "/Users/yann/codes/temp/icarus-poc/js-cardano-wasm/rust/cardano-c/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/Users/yann/codes/temp/icarus-poc/js-cardano-wasm/rust/cardano-c/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/Users/yann/codes/temp/icarus-poc/js-cardano-wasm/rust/cardano-c/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "/Users/yann/codes/temp/icarus-poc/js-cardano-wasm/rust/cardano-c/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/Users/yann/codes/temp/icarus-poc/js-cardano-wasm/rust/cardano-c/NDK/x86/bin/i686-linux-android-ar"
linker = "/Users/yann/codes/temp/icarus-poc/js-cardano-wasm/rust/cardano-c/NDK/x86/bin/i686-linux-android-clang"
